In [7]:
import numpy as np
import sys
import os
sys.path.insert(0, os.path.abspath('../src'))
from experiment.network_generator import gen_network

In [21]:
C = 2
U = 10
H = 3
D = 7
X = np.random.choice([0,1], size=(C,U,H,D))
a_uv, grph = gen_network(seed=142, p=0.03, n=U, m=None, drop_prob=None, net_type='erdos')

In [22]:
display(X.shape)
display(a_uv.shape)

(2, 10, 3, 7)

(10, 10)

In [25]:
X_p = (X.sum(axis=(2,3))>0).astype(int)

In [53]:
a=np.array([[0,1,1],[1,0,1],[1,1,0]])
X_cu = np.array([[1,0,0],[0,1,0]]).T

In [54]:
display('A')
display(a)
display('X')
display(X_cu)

'A'

array([[0, 1, 1],
       [1, 0, 1],
       [1, 1, 0]])

'X'

array([[1, 0],
       [0, 1],
       [0, 0]])

In [51]:
(a.dot(X_cu) + X_cu)

array([[1, 1],
       [1, 1],
       [1, 1]])

In [50]:
((a.dot(X_cu) + X_cu)>0).astype(int)

array([[1, 1],
       [1, 1],
       [1, 1]])

In [58]:
(np.matmul(a,X_cu)+X_cu>0).astype(int)

array([[1, 1],
       [1, 1],
       [1, 1]])

In [68]:
sorted(grph.degree, key=lambda x: x[1], reverse=True)

[(3, 1),
 (4, 1),
 (5, 1),
 (6, 1),
 (7, 1),
 (9, 1),
 (0, 0),
 (1, 0),
 (2, 0),
 (8, 0)]

In [66]:
for u in list(map(lambda x: x[0], sorted(grph.degree, key=lambda x: x[1], reverse=True))):
  print(u)

3
4
5
6
7
9
0
1
2
8
